// "Find elsewhere": links that search other sites (torrents, streaming services, subtitles…) for
// the open title, built from IMDb Scout Mod's site list (scout-sites.ts, generated by
// scripts/extract-scout-sites.mjs). Links only: nothing here contacts the sites.
import type { ScoutCategory, ScoutSettings } from './types';

export interface ScoutSite {
  /** Stable key: the name, plus `-tv` for a series-only twin of a movie entry. */
  id: string;
  name: string;
  category: ScoutCategory;
  /** URL template with upstream's placeholders: %tt%, %nott%, %search_string%, %year%… */
  searchUrl: string;
  /** Where the link goes when that isn't searchUrl (searchUrl is then an API upstream checks). */
  goToUrl?: string;
  /** Series only. */
  TV?: boolean;
  /** Movies and series (otherwise movies only). */
  both?: boolean;
  /** What spaces in the title become (default '+'). */
  spaceEncode?: string;
  /** On the short list shown first. */
  curated?: boolean;
}

/** What is known about the open title. */
export interface ScoutContext {
  /** IMDb id (tt…), once the title is matched on IMDb. */
  imdbId?: string;
  title: string;
  year?: string;
  /** `movie` | `series`. */
  kind: string;
  tmdbId?: string;
  /** The episode on screen (series), for sites that open one episode. */
  season?: number;
  episode?: number;
}

export interface ScoutLink {
  id: string;
  name: string;
  category: ScoutCategory;
  url: string;
  curated: boolean;
}

export const SCOUT_CATEGORIES: ScoutCategory[] = ['torrent', 'streaming', 'subtitles', 'usenet', 'other'];

/** Group names in English (the window translates them). */
export const SCOUT_CATEGORY_NAMES: Record<ScoutCategory, string> = {
  torrent: 'Torrents',
  streaming: 'Streaming',
  subtitles: 'Subtitles',
  usenet: 'Usenet',
  other: 'Other',
};

/** Usenet indexers only answer with an account there, so that group starts off. */
export const DEFAULT_SCOUT: ScoutSettings = {
  enabled: true,
  categories: ['torrent', 'streaming', 'subtitles', 'other'],
  allSites: false,
  autoSubtitles: true,
  openSubtitlesKey: '',
  autoSubtitleLanguage: '',
};

/**
 * The language automatic subtitles fetch, or null while they are off: "Find elsewhere" and the
 * option on, an OpenSubtitles key, subtitles not turned off, and a language (the subtitle setting's,
 * unless one is chosen for them; "Ask every time" alone names none).
 */
export function autoSubtitleLanguage(scout: ScoutSettings, subtitles: string): string | null {
  if (!scout.enabled || !scout.autoSubtitles || !scout.openSubtitlesKey.trim() || subtitles === 'off') return null;
  const language = scout.autoSubtitleLanguage || subtitles;
  return language && language !== 'ask' && language !== 'off' ? language : null;
}

// Every placeholder upstream knows (the TVDb, TVmaze and Douban ones never get a value here).
const PARAM = /%(tt|nott|tvdbid|tvmazeid|tmdbid|tmdb_orig_title|doubanid|search_string_orig|search_string|year|seriesid|seasonid|episodeid)%/g;

const isSeries = (kind: string) => /series|tv/i.test(kind);

/** The placeholder values `ctx` provides; a site that needs one it lacks is left out. */
function values(ctx: ScoutContext, space: string): Record<string, string | undefined> {
  const id = ctx.imdbId && /^tt\d+$/.test(ctx.imdbId) ? ctx.imdbId : undefined;
  // As upstream does: a " (…)" tail, "&" and ":" go, and spaces become the site's separator. Each
  // word is encoded as well, so a "?", "#" or "/" in a title can't break the link.
  const words = ctx.title.trim().replace(/ +\(.*|&|:/g, '').split(/\s+/).filter(Boolean);
  const search = words.length ? words.map(encodeURIComponent).join(space) : undefined;
  const episode = isSeries(ctx.kind) && ctx.season && ctx.episode;
  return {
    tt: id,
    nott: id?.slice(2),
    tmdbid: ctx.tmdbId,
    search_string: search,
    // Upstream's original-language title; the app knows one title.
    search_string_orig: search,
    year: /\d{4}/.exec(ctx.year ?? '')?.[0],
    seriesid: episode ? id : undefined,
    seasonid: episode ? String(ctx.season) : undefined,
    episodeid: episode ? String(ctx.episode) : undefined,
  };
}

/** `template` filled in for the title, or null when it needs something `ctx` doesn't have. */
export function buildScoutUrl(template: string, ctx: ScoutContext, spaceEncode = '+'): string | null {
  const vals = values(ctx, spaceEncode);
  let missing = false;
  const filled = template
    .replace(PARAM, (_, key: string) => {
      const v = vals[key];
      if (v === undefined) missing = true;
      return v ?? '';
    })
    .replace(/---/g, '-'); // a " - " in a title, on sites that use "-" for spaces
  if (missing) return null;
  try {
    // Percent-encodes the spaces and quotes some templates have.
    return new URL(filled).href;
  } catch {
    return null;
  }
}

/** The sites for this kind of title: series get TV-only and both, movies (or unknown) the rest. */
export function sitesForTitle(sites: ScoutSite[], ctx: ScoutContext): ScoutSite[] {
  const series = isSeries(ctx.kind);
  return sites.filter((s) => s.both || (series ? s.TV : !s.TV));
}

// Language tags subtitle sites carry in their names ("OpenSubtitles (EN)", "Subs4free (GR|EN)"),
// by the names the subtitle setting uses.
const SUBTITLE_TAGS: Record<string, string[]> = {
  english: ['EN'],
  arabic: ['ARABIC'],
  chinese: ['CN'],
  dutch: ['NL'],
  french: ['FR'],
  german: ['DE'],
  greek: ['GR'],
  hebrew: ['IL'],
  italian: ['IT'],
  polish: ['PL'],
  portuguese: ['PT', 'BR'],
  romanian: ['RO'],
  russian: ['RU'],
  spanish: ['ES'],
  turkish: ['TR'],
};

const siteTags = (name: string) => /\(([^)]+)\)\s*$/.exec(name)?.[1].toUpperCase().split('|') ?? [];

/**
 * The subtitle links, for the subtitle setting `language` (a language, 'off' or 'ask'): sites for
 * that language first, then sites for every language, then sites for other languages.
 */
export function subtitleLinks(links: ScoutLink[], language: string): ScoutLink[] {
  const want = SUBTITLE_TAGS[language.trim().toLowerCase()] ?? [];
  const rank = (l: ScoutLink) => {
    const tags = siteTags(l.name);
    return !tags.length ? 1 : tags.some((tag) => want.includes(tag)) ? 0 : 2;
  };
  // A stable sort: within each rank the catalog's order (the short list first) stays.
  return links.filter((l) => l.category === 'subtitles').sort((a, b) => rank(a) - rank(b));
}

/** Links for the title, in catalog order (sites that need an IMDb id the title lacks are left out). */
export function scoutLinks(sites: ScoutSite[], ctx: ScoutContext): ScoutLink[] {
  const links: ScoutLink[] = [];
  for (const s of sitesForTitle(sites, ctx)) {
    const url = buildScoutUrl(s.goToUrl ?? s.searchUrl, ctx, s.spaceEncode);
    if (url) links.push({ id: s.id, name: s.name, category: s.category, url, curated: Boolean(s.curated) });
  }
  return links;
}
